# Generated by Django 4.0.4 on 2023-10-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('STOP_LOSS', 'Stop Loss'), ('TAKE_PROFIT', 'Take Profit')], default='BUY', max_length=20)),
                ('status', models.CharField(default='open', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('take_profit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
